### ISSUE TITLE
Does not advertise properly on stm32

### ISSUE THREAD

**Issue by gigaj0ule** [khoih-prog/MDNS_Generic#11]
I have been trying out the library on STM32F103 with the wiznet 5500 chip, and Ethernet_Generic library.

I'm able to discover services well, and my QM packets are answered with the responses processed nicely.

```
27755	509.550094542	10.0.0.242	224.0.0.251	MDNS	86	Standard query 0x0000 PTR _http._tcp.local, "QM" question
```

```
Discovering services of type '_http' via Bonjour...
Found: 'EPSON XP-810 Series' at 10.0.0.225:80
Found: '_printer' at 10.0.0.110:23595
Found: '_ipp' at 10.0.0.110:2049
Found: '_http' at 0.0.0.0:16723
Found: 'EPSON XP-810 Series' at 10.0.0.225:80
Found: '_scanner' at 10.0.0.225:2049
Found: '_ipp' at 0.0.0.0:16723
Found: 'EPSON XP-810 Series' at 10.0.0.225:80
Found: 'EPSON XP-810 Series' at 10.0.0.225:80
Found: '_ipp' at 0.0.0.0:16723
Finished discovering services of type _http
```

Curiously the service browser returns more than _http...

But more seriously, I cannot seem to get my service recognized by mdns-scan

I have confirmed that wireshark can see my packets:

```
27996	512.433768171	10.0.0.242	224.0.0.251	MDNS	291	Standard query response 0x0000 SRV, cache flush 0 0 80 arduino.local TXT, cache flush PTR _http._tcp.local PTR arduino._http._tcp.local A, cache flush 10.0.0.242
```

But perhaps they are malformed?

```
0000   00 02 00 01 00 06 2c f7 f1 08 0e 9e 00 00 08 00   ......,.........
0010   45 00 01 13 03 0c 40 00 80 11 0a e1 0a 00 00 f2   E.....@.........
0020   e0 00 00 fb 14 e9 14 e9 00 ff d4 5f 00 00 84 00   ..........._....
0030   00 00 00 04 00 00 00 01 07 61 72 64 75 69 6e 6f   .........arduino
0040   05 5f 68 74 74 70 04 5f 74 63 70 05 6c 6f 63 61   ._http._tcp.loca
0050   6c 00 00 21 80 01 00 00 00 0a 00 15 00 00 00 00   l..!............
0060   00 50 07 61 72 64 75 69 6e 6f 05 6c 6f 63 61 6c   .P.arduino.local
0070   00 07 61 72 64 75 69 6e 6f 05 5f 68 74 74 70 04   ..arduino._http.
0080   5f 74 63 70 05 6c 6f 63 61 6c 00 00 10 80 01 00   _tcp.local......
0090   00 00 0a 00 01 00 09 5f 73 65 72 76 69 63 65 73   ......._services
00a0   07 5f 64 6e 73 2d 73 64 04 5f 75 64 70 05 6c 6f   ._dns-sd._udp.lo
00b0   63 61 6c 00 00 0c 00 01 00 00 00 0a 00 12 05 5f   cal............_
00c0   68 74 74 70 04 5f 74 63 70 05 6c 6f 63 61 6c 00   http._tcp.local.
00d0   05 5f 68 74 74 70 04 5f 74 63 70 05 6c 6f 63 61   ._http._tcp.loca
00e0   6c 00 00 0c 00 01 00 00 00 0a 00 1a 07 61 72 64   l............ard
00f0   75 69 6e 6f 05 5f 68 74 74 70 04 5f 74 63 70 05   uino._http._tcp.
0100   6c 6f 63 61 6c 00 07 61 72 64 75 69 6e 6f 05 6c   local..arduino.l
0110   6f 63 61 6c 00 00 01 80 01 00 00 00 0a 00 04 0a   ocal............
0120   00 00 f2                                          ...
```

I did find an error in the library which is suspicious:

```
          if (NULL != textContent) 
          {
            record->textContent = (uint8_t*)my_malloc(strlen((char*)textContent));
            
            if (NULL == record->textContent)
              goto errorReturn;

            strcpy((char*)record->textContent, textContent);
          }
```

If textContent is not NULL then strcpy will copy text into the packet but nothing changes the payload length byte in the packet so the text itself is interpreted as the payload length byte and the packet becomes malformed. 

Advertising with text explicitly set to NULL seems to bypass this problem

```
mdns.addServiceRecord("arduino._http", 80, MDNSServiceTCP, NULL) 
```

**Comment by gigaj0ule** [comment]
More clues: in avahi-browse i'm seeing what looks like buffer overrun in the name 0_o

```
+ wlp3s0 IPv4 my_arduino                                    _http\028._tcp       local
```

**Comment by khoih-prog** [comment]
Hi @gigaj0ule 

> I'm able to see arduino with avahi-browse, but not mdns-scan

Can you check to be sure `mdns-scan` is fully compatible and OK to use? Also check using other better boards (STM32F4/F7, etc), or the original [**ArduinoMDNS**](https://github.com/arduino-libraries/ArduinoMDNS) library, if possible, to isolate the issue (STM32 F1 board, Ethernet, this library's bug, etc.)

Anyway, I'll archive this library soon as I won't have time to spend on this library anymore.

Your investigation, updated info, PR are appreciated to help other users.

Best Regards,

**Comment by gigaj0ule** [comment]
I need to do more looking into mdns-scan to know where the bug is exactly. 

I'll keep digging! 

As this is the only ethernet-compatible mDNS library for Arduino, I am not sure why you would want to archive it?

**Comment by khoih-prog** [comment]
> As this is the only recently-maintained ethernet-compatible mDNS library for Arduino, I am not sure why you would want to archive it?

I'm sorry I really don't have time to spend on this library and mDNS topic for quite a long time. It's hard and time-consuming to start over every time to reread all the necessary info / specs.

Hopefully someone (you ???) will take over and maintain this library. Before that time, I'm still trying my best and really appreciate any contribution (bug fix, PR, etc.)

It's good you're making some progress.

**Comment by gigaj0ule** [comment]
Time ah yes, the one thing I can't buy more of x_x

Well good news is... it looks like this unmerged PR fixes the overrun problem I just noticed!

https://github.com/arduino-libraries/ArduinoMDNS/pull/8/commits/396aef16a2826e6f3207f7444251eae322251ca5

\028 is no longer reported at the end of _http

**Comment by khoih-prog** [comment]
If tested OK and problem fixed, could you make the PR? Thanks

**Comment by gigaj0ule** [comment]
Not sure entirely, I still have more acid tests to run before I'm satisfied that these bugs are fixed :-)
