### ISSUE TITLE
ESP32 - WiFiResolvingHostNames

### ISSUE THREAD

**Issue by patricksebastien** [khoih-prog/MDNS_Generic#9]
Hi,

I am trying to use this library on a ESP32 to search for a software listening on port 12101 UDP. I want to get the IP. So trying to use the example WiFiResolvingHostNames, I get an error whatever the hostname I try. It works using avahi:
`avahi-browse -r _touchoscbridge._udp`

Output is something like this:
`+ wlp4s10f4 IPv4 DESKTOP-OOOO                               _touchoscbridge._udp local`

So what I should search in the Serial terminal? I tried all combo: touchoscbridge, _touchoscbridge, _touchoscbridge._udp.

Also I have an issue with the last character being stipped. I think we can safely remove this?
```
if (length > 1)
    length = (length - 2) % 256;
```
https://github.com/khoih-prog/MDNS_Generic/blob/master/examples/WiFi/WiFiResolvingHostNames/WiFiResolvingHostNames.ino#L276
_Resolving '_touchoscbridge._ud' error._

Thanks

**Comment by khoih-prog** [comment]
For ESP32, it's better to use **ESP32-native mDNS service.**

Check 

1. [**mDNS Service**](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mdns.html)
2. [**ESPmDNS** library](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESPmDNS)

If still not successful, post an issue on [**ESP32 issues**](https://github.com/espressif/arduino-esp32/issues). Remember to post [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example)

Without ways to duplicate, it's impossible to know where is wrong to fix and the issue will be ignored.

I'm closing this issue now, and won't reopen until you prove there is a bug of this library.

Good Luck,
